name: CMake Build Matrix

# Controls when the action will run. Triggers the workflow on push
on: 
  repository_dispatch:
    types: [manual]
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.arch }}-${{ matrix.python_version }}-${{ matrix.generator }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: ["Release"]
        arch: ["x86"]
        python_version: [3.6]
        generator: ["Unix Makefiles"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Print variables
        run: |
          echo "${{ github.workspace }}"
          echo "${{ github.home}}"
          echo $HOME

      - name: Modify path
        shell: bash
        run: |
          # strings.exe was installed in repo root by install_prereqs
          echo -e "${{ github.workspace }}/PATH1:$(cat $GITHUB_PATH)" > $GITHUB_PATH
          echo "$PATH"

      - name: Modify path2
        shell: bash
        run: |
          # strings.exe was installed in repo root by install_prereqs
          echo "${{ github.workspace }}/PATH2" >> $GITHUB_PATH
          echo "$PATH"

      - name: Modify path3
        run: |
          echo "${{ github.worksapce }}/PATH3" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Print path3
        run: |
          echo "$PATH"


      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          echo $TRIPLET
          echo $TRIPLET_FILENAME
     
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

